#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: make
#
Name     : PyQt5
Version  : 5.15.9
Release  : 43
URL      : https://files.pythonhosted.org/packages/5c/46/b4b6eae1e24d9432905ef1d4e7c28b6610e28252527cdc38f2a75997d8b5/PyQt5-5.15.9.tar.gz
Source0  : https://files.pythonhosted.org/packages/5c/46/b4b6eae1e24d9432905ef1d4e7c28b6610e28252527cdc38f2a75997d8b5/PyQt5-5.15.9.tar.gz
Summary  : Python bindings for the Qt cross platform application toolkit
Group    : Development/Tools
License  : GPL-3.0
Requires: PyQt5-bin = %{version}-%{release}
Requires: PyQt5-license = %{version}-%{release}
Requires: PyQt5-python = %{version}-%{release}
Requires: PyQt5-python3 = %{version}-%{release}
BuildRequires : PyQt5-data
BuildRequires : buildreq-kde
BuildRequires : dbus-python
BuildRequires : dbus-python-dev
BuildRequires : mesa-dev
BuildRequires : pkgconfig(dbus-1)
BuildRequires : pypi(pyqt_builder)
BuildRequires : pypi(toml)
BuildRequires : pypi-pyqt5_sip
BuildRequires : python3
BuildRequires : python3-dev
BuildRequires : qscintilla
BuildRequires : qscintilla-dev
BuildRequires : qtbase-dev
BuildRequires : qtcanvas3d
BuildRequires : qtcharts-dev
BuildRequires : qtconnectivity-dev
BuildRequires : qtdeclarative-dev
BuildRequires : qtgraphicaleffects
BuildRequires : qtimageformats-dev
BuildRequires : qtlocation-dev
BuildRequires : qtmultimedia-dev
BuildRequires : qtquickcontrols
BuildRequires : qtquickcontrols2
BuildRequires : qtscript-dev
BuildRequires : qtscxml-dev
BuildRequires : qtsensors-dev
BuildRequires : qtserialbus-dev
BuildRequires : qtserialport-dev
BuildRequires : qtsvg-dev
BuildRequires : qttools-dev
BuildRequires : qttranslations
BuildRequires : qtvirtualkeyboard-dev
BuildRequires : qtwebchannel-dev
BuildRequires : qtwebengine-dev
BuildRequires : qtwebsockets-dev
BuildRequires : qtx11extras-dev
BuildRequires : qtxmlpatterns-dev
BuildRequires : sip
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
PyQt5 - Comprehensive Python Bindings for Qt v5
===============================================

%package bin
Summary: bin components for the PyQt5 package.
Group: Binaries
Requires: PyQt5-license = %{version}-%{release}

%description bin
bin components for the PyQt5 package.


%package license
Summary: license components for the PyQt5 package.
Group: Default

%description license
license components for the PyQt5 package.


%package python
Summary: python components for the PyQt5 package.
Group: Default
Requires: PyQt5-python3 = %{version}-%{release}
Provides: pyqt5-python

%description python
python components for the PyQt5 package.


%package python3
Summary: python3 components for the PyQt5 package.
Group: Default
Requires: python3-core

%description python3
python3 components for the PyQt5 package.


%prep
%setup -q -n PyQt5-5.15.9
cd %{_builddir}/PyQt5-5.15.9

%build
## build_prepend content
sip-build --no-make --confirm-license
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1683322922
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
## make_prepend content
cd build
## make_prepend end
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1683322922
rm -rf %{buildroot}
## install_prepend content
cd build
## install_prepend end
mkdir -p %{buildroot}/usr/share/package-licenses/PyQt5
cp %{_builddir}/PyQt5-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/PyQt5/8624bcdae55baeef00cd11d5dfcfa60f68710a02 || :
%make_install
## install_append content
find %{buildroot} -name '*.so' -print0 | xargs -rt0 chmod 755 --
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pylupdate5
/usr/bin/pyrcc5
/usr/bin/pyuic5

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/PyQt5/8624bcdae55baeef00cd11d5dfcfa60f68710a02

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
