#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: make
# autospec version: v27
# autospec commit: 6aaa12f
#
Name     : PyQt5
Version  : 5.15.11
Release  : 51
URL      : https://files.pythonhosted.org/packages/0e/07/c9ed0bd428df6f87183fca565a79fee19fa7c88c7f00a7f011ab4379e77a/PyQt5-5.15.11.tar.gz
Source0  : https://files.pythonhosted.org/packages/0e/07/c9ed0bd428df6f87183fca565a79fee19fa7c88c7f00a7f011ab4379e77a/PyQt5-5.15.11.tar.gz
Summary  : Python bindings for the Qt cross platform application toolkit
Group    : Development/Tools
License  : GPL-3.0
Requires: PyQt5-bin = %{version}-%{release}
Requires: PyQt5-lib = %{version}-%{release}
Requires: PyQt5-license = %{version}-%{release}
Requires: PyQt5-python = %{version}-%{release}
Requires: PyQt5-python3 = %{version}-%{release}
BuildRequires : buildreq-kde
BuildRequires : dbus-python
BuildRequires : dbus-python-dev
BuildRequires : mesa-dev
BuildRequires : pkgconfig(dbus-1)
BuildRequires : pypi(pyqt_builder)
BuildRequires : pypi-pyqt5_sip
BuildRequires : python3
BuildRequires : python3-dev
BuildRequires : qscintilla
BuildRequires : qscintilla-dev
BuildRequires : qtbase-dev
BuildRequires : qtcharts-dev
BuildRequires : qtconnectivity-dev
BuildRequires : qtdeclarative-dev
BuildRequires : qtgraphicaleffects
BuildRequires : qtimageformats-dev
BuildRequires : qtlocation-dev
BuildRequires : qtmultimedia-dev
BuildRequires : qtquickcontrols
BuildRequires : qtquickcontrols2
BuildRequires : qtscript-dev
BuildRequires : qtscxml-dev
BuildRequires : qtsensors-dev
BuildRequires : qtserialbus-dev
BuildRequires : qtserialport-dev
BuildRequires : qtsvg-dev
BuildRequires : qttools-dev
BuildRequires : qttranslations
BuildRequires : qtvirtualkeyboard-dev
BuildRequires : qtwebchannel-dev
BuildRequires : qtwebengine-dev
BuildRequires : qtwebsockets-dev
BuildRequires : qtx11extras-dev
BuildRequires : qtxmlpatterns-dev
BuildRequires : sip
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
PyQt is supplied with a number of example applications and demonstrations that
have been written to provide developers with examples of the Qt API in use,
highlight good programming practise, and showcase features found in each of
Qt's core technologies.

%package bin
Summary: bin components for the PyQt5 package.
Group: Binaries
Requires: PyQt5-license = %{version}-%{release}

%description bin
bin components for the PyQt5 package.


%package lib
Summary: lib components for the PyQt5 package.
Group: Libraries
Requires: PyQt5-license = %{version}-%{release}

%description lib
lib components for the PyQt5 package.


%package license
Summary: license components for the PyQt5 package.
Group: Default

%description license
license components for the PyQt5 package.


%package python
Summary: python components for the PyQt5 package.
Group: Default
Requires: PyQt5-python3 = %{version}-%{release}
Provides: pyqt5-python

%description python
python components for the PyQt5 package.


%package python3
Summary: python3 components for the PyQt5 package.
Group: Default
Requires: python3-core
Requires: pypi-pyqt5_sip

%description python3
python3 components for the PyQt5 package.


%prep
%setup -q -n PyQt5-5.15.11
cd %{_builddir}/PyQt5-5.15.11

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1748988021
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
## make_prepend content
export PATH="/usr/lib64/qt5/bin:$PATH"
sip-build --no-make --confirm-license
cd build
## make_prepend end
make  %{?_smp_mflags}


%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1748988021
rm -rf %{buildroot}
## install_prepend content
export PATH="/usr/lib64/qt5/bin:$PATH"
cd build
## install_prepend end
mkdir -p %{buildroot}/usr/share/package-licenses/PyQt5
cp %{_builddir}/PyQt5-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/PyQt5/8624bcdae55baeef00cd11d5dfcfa60f68710a02 || :
export GOAMD64=v2
GOAMD64=v2
%make_install
## install_append content
find %{buildroot} -name '*.so' -print0 | xargs -rt0 chmod 755 --
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pylupdate5
/usr/bin/pyrcc5
/usr/bin/pyuic5

%files lib
%defattr(-,root,root,-)
/usr/lib64/qt5/plugins/PyQt5/libpyqt5qmlplugin.so
/usr/lib64/qt5/plugins/designer/libpyqt5.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/PyQt5/8624bcdae55baeef00cd11d5dfcfa60f68710a02

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
